version: '3.8'

services:
  ium_service:
    image: dbarania/ium_summary_app
    container_name: ium-summary-srv
    ports:
      - "8000:8000"
    environment:
      - INSUFFICIENT_VRAM=${INSUFFICIENT_VRAM:-true}
    volumes:
      - ./summary_logs:/app/logs
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
